version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8000"
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=demo
    ports:
      - "5433:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


